logging:
  file:
    path: ./logs # 相对于项目根路径
    name: ${logging.file.path}/application.log
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/%d{yyyy-MM-dd}.%i.log
      max-file-size: 32MB
      max-history: 16 # 单位为天
  level:
    org.kagura: debug
    org.springframework:
      web.servlet:
        DispatcherServlet: debug
        mvc.method.annotation.RequestMappingHandlerMapping: debug
      security.web.DefaultSecurityFilterChain: debug
      transaction.interceptor.TransactionInterceptor: trace
    org.hibernate:
      SQL: debug
      orm.jdbc.bind: trace

server:
  servlet:
    context-path: /api

spring:
  application:
    name: talk
  config:
    import:
      - optional:file:.env.local[.properties] # 模拟环境变量文件读取
  mvc:
    problemdetails:
      enabled: true
  security:
    login: /auth/login
    jwt: # 弃用对称密钥签名，采用更安全的非对称密钥签名
      issuer: Kagura
      keypair: jwt
      expiration: 3600 # 有效时长，单位为秒
    cors:
      origins: ${CORS_HOSTS}
      methods: GET,POST,PUT,DELETE,OPTIONS
    oauth2:
      redirect: /auth/redirect
      length: 32 # 随机密码长度
      cookie: # 出于无状态考虑，state 参数通过 cookie 存储
        name: oauth2_state
        age: 300 # 有效时长，单位为秒
      client:
        registration:
          github:
            client-id: ${GITHUB_OAUTH2_CLIENT_ID}
            client-secret: ${GITHUB_OAUTH2_CLIENT_SECRET}
            redirect-uri: "{baseUrl}${spring.security.oauth2.redirect}/{registrationId}"
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        order_updates: true
        jdbc:
          batch_size: 50 # 建议设置为实体 id 字段 @SequenceGenerator 注解 allocationSize 属性的值
          batch_versioned_data: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE}?reWriteBatchedInserts=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
