logging:
  file:
    path: ./logs # 相对于项目根路径
    name: ${logging.file.path}/application.log
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/%d{yyyy-MM-dd}.%i.log
      max-file-size: 32MB
      max-history: 16 # 单位为天
  level:
    org.kagura: debug
    org.springframework:
      web.servlet:
        DispatcherServlet: debug
        mvc.method.annotation.RequestMappingHandlerMapping: debug

server:
  servlet:
    context-path: /api

spring:
  application:
    name: talk
  config:
    import:
      - optional:file:.env.local[.properties]
  mvc:
    problemdetails:
      enabled: true
  security:
    login: /auth/login
    jwt:
      issuer: Kagura
      secret: ${JWT_SECRET}
      expiration: 3600 # 有效时长，单位为秒
    cors:
      origins: ${CORS_HOSTS}
      methods: ${CORS_METHODS}
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_OAUTH2_CLIENT_ID}
            client-secret: ${GITHUB_OAUTH2_CLIENT_SECRET}
  jpa:
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE}?reWriteBatchedInserts=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
